export default function questionCategories () {
    return [{"label":"Adult"},
    {"label":"Arts & Entertainment"},
    {"label":"Autos & Vehicles"},
    {"label":"Beauty & Fitness"},
    {"label":"Books & Literature"},
    {"label":"Business & Industrial"},
    {"label":"Computers & Electronics"},
    {"label":"Finance"},
    {"label":"Food & Drink"},
    {"label":"Games"},
    {"label":"Health"},
    {"label":"Hobbies & Leisure"},
    {"label":"Home & Garden"},
    {"label":"Internet & Telecom"},
    {"label":"Jobs & Education"},
    {"label":"Law & Government"},
    {"label":"News"},
    {"label":"Online Communities"},
    {"label":"People & Society"},
    {"label":"Pets & Animals"},
    {"label":"Real Estate"},
    {"label":"General Knowledge"},
    {"label":"Science"},
    {"label":"Sensitive Subjects"},
    {"label":"Shopping"},
    {"label":"Sports"},
    {"label":"Travel"}
    ]
}
